### ISSUE TITLE
NullPointerException while handling MovePlayerPacket

### ISSUE THREAD

**Issue by Polyana-Fontes** [Creeperface01/GAC#20]
Hello,

Some users reported a NullPointerException when GAC is reverting movement from fly hackers, the exception is spammed in the console and JVM eventually disables the stack trace of that position when `-XX:-OmitStackTraceInFastThrow` is not present in the startup parameters.

While investigating I noticed that this section isn't doing a null check on `forceMovement`, which is a nullable platform field, Kotlin might be interpreting it as a mutable `Vector3!` type so it cannot smart-cast to `Vector3` and neither to `Vector3?`, then it disables the null safety in that field. `sendPosition` parameters aren't annotated either, but if it receives a null value in the first param, it will throw a NullPointeerException
https://github.com/Creeperface01/GAC/blob/2dfeb39616e372ef43f5092e8af4a060b8dc8fbd/src/main/java/cz/creeperface/nukkit/gac/player/CheatPlayer.kt#L98-L100

Here is the exception that was caught while running the GAC plugin in PowerNukkit:
```java
2020-08-27 12:52:30.524 [main] WARN  - Error whilst processing the packet 19:MovePlayerPacket for <playerName> (full data: MovePlayerPacket(eid=60500, x=<pos>, y=<pos>, z=<pos>, yaw=-20.889954, headYaw=339.11005, pitch=54.265854, mode=0, onGround=false, ridingEid=0, int1=0, int2=0))
java.lang.NullPointerException: null
    at cn.nukkit.Player.sendPosition(Player.java:4491) ~[server.jar:?]
    at cn.nukkit.Player.sendPosition(Player.java:4485) ~[server.jar:?]
    at cz.creeperface.nukkit.gac.V.a(Unknown Source) ~[?:?]
    at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
    at cn.nukkit.network.Network.lambda$processPackets$3(Network.java:285) ~[server.jar:?]
    at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_262]
    at cn.nukkit.network.Network.processPackets(Network.java:283) [server.jar:?]
    at cn.nukkit.network.Network.processBatch(Network.java:269) [server.jar:?]
    at cn.nukkit.Player.handleDataPacket(Player.java:2200) [server.jar:?]
    at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
    at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:75) [server.jar:?]
    at cn.nukkit.network.Network.processInterfaces(Network.java:158) [server.jar:?]
    at cn.nukkit.Server.tick(Server.java:1297) [server.jar:?]
    at cn.nukkit.Server.tickProcessor(Server.java:1080) [server.jar:?]
    at cn.nukkit.Server.start(Server.java:1048) [server.jar:?]
    at cn.nukkit.Server.<init>(Server.java:704) [server.jar:?]
    at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
```

If you would like to see a related debugpaste, it's available here:
https://debugpaste.powernukkit.org/pastes/uterugupik.html

**Comment by RealTriassic** [comment]
I'm having this issue on PowerNukkit 1.4.0.0 too, though i'm sure this will never be fixed as this is modded nukkit...

**Comment by Creeperface01** [comment]
Ah I must have not noticed that. Anyway it looks like I shouldn't clear lines tables during obfuscation

**Comment by Creeperface01** [comment]
Should be fixed
