### ISSUE TITLE
Console exception spam

### ISSUE THREAD

**Issue by tim-van-dijkhuizen** [Creeperface01/GAC#3]
I get this error very often, would you be able to fix it? Thanks!
```
---> 20:59:01 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerTeleportEvent" to "GAC v1.0.3": lateinit property player has not been initialized on cz.creeperface.nukkit.gac.C
---> 20:59:01 [ERROR] Throwing
---> kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
--->    at cz.creeperface.nukkit.gac.p.a(Unknown Source) ~[?:?]
--->    at cz.creeperface.nukkit.gac.C.a(Unknown Source) ~[?:?]
--->    at cz.creeperface.nukkit.gac.J.invoke(Unknown Source) ~[?:?]
--->    at cz.creeperface.nukkit.gac.am.execute(Unknown Source) ~[?:?]
--->    at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit.jar:?]
--->    at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit.jar:?]
--->    at cn.nukkit.Player.teleport(Player.java:4161) [nukkit.jar:?]
--->    at cn.nukkit.entity.Entity.teleport(Entity.java:2091) [nukkit.jar:?]
--->    at nl.dodocraft.utils.world.WorldManager.onPlayerJoin(WorldManager.java:36) [DodoUtils-1.0.0.jar:?]
--->    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
--->    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
--->    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
--->    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
--->    at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) [nukkit.jar:?]
--->    at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) [nukkit.jar:?]
--->    at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit.jar:?]
--->    at cn.nukkit.Player.doFirstSpawn(Player.java:871) [nukkit.jar:?]
--->    at cn.nukkit.Player.sendNextChunk(Player.java:824) [nukkit.jar:?]
--->    at cn.nukkit.Player.checkNetwork(Player.java:1831) [nukkit.jar:?]
--->    at cn.nukkit.Server.tick(Server.java:1150) [nukkit.jar:?]
--->    at cn.nukkit.Server.tickProcessor(Server.java:916) [nukkit.jar:?]
--->    at cn.nukkit.Server.start(Server.java:893) [nukkit.jar:?]
--->    at cn.nukkit.Server.<init>(Server.java:578) [nukkit.jar:?]
--->    at cn.nukkit.Nukkit.main(Nukkit.java:117) [nukkit.jar:?]
```

**Comment by Creeperface01** [comment]
Your plugin list?

**Comment by tim-van-dijkhuizen** [comment]
GAC, kotlinlib and everything else is custom. Sorry forgot about that. Can this be caused by a plugin? If so any idea how? Then I can look into it.
